apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github: 
        owner: bernardolsp
        repo: descomplicando-gitops-no-kubernetes-argocd
        tokenRef:
          secretName: github-token
          key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: "stack-apps-{{branch_slug}}-{{number}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bernardolsp/descomplicando-gitops-no-kubernetes-argocd.git
        targetRevision: '{{head_sha}}'
        path: app-of-apps/
        helm:
          parameters:
          - name: "argocd.giropopsSenhas.enabled"
            value: "true"
          - name: "argocd.randomLogger.enabled"
            value: "true"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'stack-apps-{{branch_slug}}-{{number}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true